[package]
name = "the-green-duck"
version = "0.1.0"
authors = ["Adam Cowdy <cowdyadam@gmail.com>"]
edition = "2018"

[dependencies.sdl2]
version = "0.34.2"
default-features = false
features = ["ttf", "gfx", "image"]
